### ISSUE TITLE
Probably worth adding a license to the repo

### ISSUE THREAD

**Issue by naupaka** [alxsimon/ecoevo.social-docs#2]
Perhaps CC-0 or CC-BY?

**Comment by alxsimon** [comment]
Hmm, I'll reopen as I still need to figure out how to show it on the book website.

**Comment by naupaka** [comment]
Looks like you can add it in the footer"
https://quarto.org/docs/reference/projects/websites.html#footer

**Comment by alxsimon** [comment]
Closed by #5
