### ISSUE TITLE
Add list of admin and moderators for transparency

### ISSUE THREAD

**Issue by alxsimon** [alxsimon/ecoevo.social-docs#23]
There is no easy to access that info from Mastodon.
A list needs to be included here.

It might be possible to write a script that uses the API to retrieve the list of admin and moderators.

Will need some time to figure this out.

**Comment by naupaka** [comment]
This is a great idea. Script can wait, I imagine, but would be great to have automated over time.

**Comment by alxsimon** [comment]
Yes, I'll do it manually for the time being.

**Comment by alxsimon** [comment]
closed by [b19e4f6](https://github.com/alxsimon/ecoevo.social-docs/commit/b19e4f66b4704bb3eb1823c9e846d2d8186baae7)
