### ISSUE TITLE
May want to add a link to the hosting terms of service since they include a lot of things people would be interested in knowing

### ISSUE THREAD

**Issue by naupaka** [alxsimon/ecoevo.social-docs#7]
Something like, 

"The hosting service that is used for ecoevo.social is called [Masto.host](https://masto.host). In order to remain in good standing with this provider, we are obligated to follow their terms of service, which are [available here](https://masto.host/tos/)."

I could submit a PR with this if you agree.

**Comment by naupaka** [comment]
Addressed in #17

**Comment by alxsimon** [comment]
Closed by #17
