### ISSUE TITLE
etiquette of Twitter blue tick use?

### ISSUE THREAD

**Issue by alxsimon** [alxsimon/ecoevo.social-docs#8]
Should we ask people to not use the emoji to fake/replicate the twitter blue tick?

I find this a weird signal that might mislead people.

**Comment by naupaka** [comment]
It does seem weird, but I imagine hard to enforce? Esp given boosting of many folks from other servers.

**Comment by alxsimon** [comment]
Yes totally, I would suggest adding that to the etiquette, not as an enforceable rule.

**Comment by alxsimon** [comment]
If need be, blue tick can be disabled by removing the availability of this custom emoji.

**Comment by naupaka** [comment]
That seems reasonable to me.

**Comment by alxsimon** [comment]
Disabled the blue checks emoji, will see if anyone complains
